//
// Created by yannik on 14.01.26.
//

#ifndef THESIS_FRAMEWORK_ERRORTYPE_HPP
#define THESIS_FRAMEWORK_ERRORTYPE_HPP

namespace graphvise {
    enum class ErrorType {
        EDGE_DOES_NOT_EXIST,
        NO_ERROR,
        EQUAL_VERTEX_IDS,
        VERTEX_ID_OUT_OF_BOUNDS,
        TOO_MANY_VERTICES_IN_SUBGRAPH,
        INVALID_SUBGRAPH_EDGE,
        DUPLICATE_EDGE,
        INVALID_VERTEX_COUNT,
        INVALID_EDGE_COUNT,
        INVALID_FORMATTING,
        FILE_NOT_FOUND,
        NOT_A_VERTEX_ID,
        INVALID_COLOR_VALUE,
        INVALID_TRANSPARENCY_VALUE,
        BACKGROUND_THREAD_ALREADY_BUSY,
        INVALID_EDGE_ID,
        INVALID_VERTEX_ID,
    };
}

#endif //THESIS_FRAMEWORK_ERRORTYPE_HPP