//
// Created by yannik on 14.01.26.
//

#ifndef THESIS_FRAMEWORK_ERRORTYPE_HPP
#define THESIS_FRAMEWORK_ERRORTYPE_HPP

namespace graphvise {
    enum class ErrorType {
        TOO_MANY_VERTICES_IN_SUBGRAPH,
        INVALID_SUBGRAPH_EDGE,
        DUPLICATE_EDGE,
        INVALID_VERTEX_COUNT,
        INVALID_EDGE_COUNT,
        INVALID_FORMATTING,
        FILE_NOT_FOUND,
        NOT_A_VERTEX_ID,
        INVALID_COLOR_VALUE,
        BACKGROUND_THREAD_ALREADY_BUSY
    };
}

#endif //THESIS_FRAMEWORK_ERRORTYPE_HPP